;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2018/10/13 下午 11:26:16

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1000	1000	; JavaEE54期英语单词表Day00 day00.htm
#define IDH_1001	1001	; JavaEE54期英语单词表Day01 day01.htm
#define IDH_1002	1002	; JavaEE54期英语单词表Day02 day02.htm
#define IDH_1003	1003	; JavaEE54期英语单词表Day03 day03.htm
#define IDH_1004	1004	; JavaEE54期英语单词表Day04 day04.htm
#define IDH_1005	1005	; JavaEE54期英语单词表Day05 day05.htm
#define IDH_1006	1006	; JavaEE54期英语单词表Day06 day06.htm
#define IDH_1007	1007	; JavaEE54期英语单词表Day07 day07.htm
#define IDH_1008	1008	; JavaEE54期英语单词表Day08 day08.htm
#define IDH_1009	1009	; JavaEE54期英语单词表Day09 day09.htm
#define IDH_1010	1010	; JavaEE54期英语单词表Day10 day10.htm
#define IDH_1011	1011	; JavaEE54期英语单词表Day11 day11.htm
#define IDH_1012	1012	; JavaEE54期英语单词表Day12 day12.htm
#define IDH_1013	1013	; JavaEE54期英语单词表Day13 day13.htm
#define IDH_1014	1014	; JavaEE54期英语单词表Day14 day14.htm
#define IDH_1015	1015	; JavaEE54期英语单词表Day15 day15.htm
#define IDH_1016	1016	; JavaEE54期英语单词表Day16 day16.htm
#define IDH_1017	1017	; JavaEE54期英语单词表Day17 day17.htm
#define IDH_1018	1018	; JavaEE54期英语单词表Day18 day18.htm
#define IDH_1019	1019	; JavaEE54期英语单词表Day19 day19.htm
