;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2018/10/13 下午 11:26:16

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1000=day00.htm	; JavaEE54期英语单词表Day00
IDH_1001=day01.htm	; JavaEE54期英语单词表Day01
IDH_1002=day02.htm	; JavaEE54期英语单词表Day02
IDH_1003=day03.htm	; JavaEE54期英语单词表Day03
IDH_1004=day04.htm	; JavaEE54期英语单词表Day04
IDH_1005=day05.htm	; JavaEE54期英语单词表Day05
IDH_1006=day06.htm	; JavaEE54期英语单词表Day06
IDH_1007=day07.htm	; JavaEE54期英语单词表Day07
IDH_1008=day08.htm	; JavaEE54期英语单词表Day08
IDH_1009=day09.htm	; JavaEE54期英语单词表Day09
IDH_1010=day10.htm	; JavaEE54期英语单词表Day10
IDH_1011=day11.htm	; JavaEE54期英语单词表Day11
IDH_1012=day12.htm	; JavaEE54期英语单词表Day12
IDH_1013=day13.htm	; JavaEE54期英语单词表Day13
IDH_1014=day14.htm	; JavaEE54期英语单词表Day14
IDH_1015=day15.htm	; JavaEE54期英语单词表Day15
IDH_1016=day16.htm	; JavaEE54期英语单词表Day16
IDH_1017=day17.htm	; JavaEE54期英语单词表Day17
IDH_1018=day18.htm	; JavaEE54期英语单词表Day18
IDH_1019=day19.htm	; JavaEE54期英语单词表Day19
